In [2]:
import pandas as pd
import numpy as np
from sklearn import linear_model
import matplotlib.pyplot as plt

In [3]:
df=pd.read_csv("F://Machine Learning GITHUB//homepricesMR.csv")
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [4]:
#data preprocessing
import math
median_bedrooms=math.floor(df.bedrooms.median())#calc median then floor to get int val and then assign to median bedrooms
median_bedrooms

3

In [5]:
df.bedrooms.fillna(median_bedrooms)    #use fillna function to fill with abv calc values

0    3.0
1    4.0
2    3.0
3    3.0
4    5.0
Name: bedrooms, dtype: float64

In [6]:
df.bedrooms=df.bedrooms.fillna(median_bedrooms) #assign to original dataset
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       3.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [7]:
reg=linear_model.LinearRegression()
reg.fit(df[["area","bedrooms","age"]],df.price)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [8]:
reg.coef_

array([   137.25, -26025.  ,  -6825.  ])

In [9]:
reg.intercept_

383724.9999999998

In [12]:
reg.predict([[3000,3,40]])

array([444400.])

In [13]:
reg.predict([[2500,4,5]])

array([588625.])