<a href="https://colab.research.google.com/github/vigneshlakshh/vigneshlakshh/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np

In [6]:
from time import process_time

Time Taken for a LIST

In [10]:
lis=[i for i in range(10000)]
start = process_time()
lisadd=[ i+5 for i in lis]
stop=process_time()
print(start)
print(stop)
print(stop-start)

9.648362283
9.649657316
0.00129503299999989


Time Taken for a Numpy

In [17]:
np_array=np.array([i for i in range(10000)])
start = process_time()
np_array += 5
stop=process_time()
print(start)
print(stop)
print(stop-start)


12.039057741
12.040006603
0.0009488619999995507


In [20]:
lis1=[1,2,3,4,5]
print(lis1)      #values are separted by, in o/P 
type(lis1)         

[1, 2, 3, 4, 5]


list

In [19]:
np_array=np.array([1,2,3,4,5])
print(np_array)    #values are not separted by, in o/P 
type(np_array)      #ndarry are n-dim array similar to matrix

[1 2 3 4 5]


numpy.ndarray

1D Array

In [24]:
#1d array
a=np.array([1,2,3,4])

In [25]:
type(a)

numpy.ndarray

In [26]:
a.shape

(4,)

2D array

In [28]:
b=np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [31]:
type(b)

numpy.ndarray

In [29]:
b.shape

(2, 4)

Floating Points array

In [33]:
c=np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(c)
print(type(c))

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]
<class 'numpy.ndarray'>


Initaial Placeholders in numpy (0's,1's)

ZEROS

In [34]:
x=np.zeros((4,5))   #shape of array you want  (rows and columns)
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


ONES

In [35]:
y=np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


PARTICULAR VALUE

In [36]:
z=np.full((5,4),5)    #mention (rows and columns), then the value you want
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


Create Identity matrix 
diag --1's
rest--0's
Rows and columns must be equal

In [37]:
a=np.eye(4) 
print(a) #CREATE 4*4

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [38]:
a=np.eye(3) 
print(a) #CREATE 3*3

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Random Values

creates a random array everytime (default it will return a float and (0-1))

In [39]:
b=np.random.random((3,4))
print(b)

[[0.32650028 0.90558848 0.1526314  0.02368534]
 [0.02850154 0.3922674  0.68609323 0.13659025]
 [0.87216213 0.03704622 0.50838283 0.85891488]]


Random INT Array with specific range 

In [44]:
c=np.random.randint(10,100,(3,5)) #any value btwn 10-100 (3*5)matrix
print(c)

[[63 72 12 21 36]
 [39 87 36 96 35]
 [22 38 52 25 17]]


Even spaced value

In [47]:
d=np.linspace(10,30,6)    #val btwn 10,30  want 6 values
print(d)

[10. 14. 18. 22. 26. 30.]


Even spaced value with step 

In [48]:
e=np.arange(10,30,5) #val btwn 10,30  stepby(or)inc by 6 values
print(e)

[10 15 20 25]


CONVERT LIST TO NUMPY ARRAY

In [51]:
lis2=[10,20,30,40,50]
print(lis2)
print(type(lis2))

np_array=np.asarray(lis2)
print(np_array)
print(type(np_array))

[10, 20, 30, 40, 50]
<class 'list'>
[10 20 30 40 50]
<class 'numpy.ndarray'>


ANALYSE A NUMPY ARRAY

In [54]:
c=np.random.randint(10,90,(5,5))
print(c)

[[58 81 18 86 41]
 [22 80 71 30 75]
 [45 53 29 35 54]
 [71 31 78 35 10]
 [27 62 59 88 28]]


In [55]:
c.shape  # (shapes of matrix)

(5, 5)

In [56]:
c.ndim  #no of dimensions

2

In [57]:
c.size  #no of elements in array

25

In [58]:
type(c)

numpy.ndarray

In [59]:
c.dtype

dtype('int64')

MATH OPERATIONS ON ARRAY

In [60]:
lis1=[1,2,3,4,5]
lis2=[6,7,8,9,10]
print(lis1+lis2) 
#in list if you add the list gets appended 

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [61]:
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])
print(a+b)    #in numpy element wise are added

[ 7  9 11 13 15]


In [63]:
c=np.random.randint(10,100,(3,3)) 
print(c)
d=np.random.randint(10,100,(3,3)) 
print(d)


[[46 66 45]
 [51 53 13]
 [56 98 94]]
[[39 35 18]
 [66 34 42]
 [80 78 79]]


In [68]:
print(c+d)
print(np.add(c,d))  #or you can mention like this

[[ 85 101  63]
 [117  87  55]
 [136 176 173]]
[[ 85 101  63]
 [117  87  55]
 [136 176 173]]


In [69]:
print(c-d)
print(np.subtract(c,d))

[[  7  31  27]
 [-15  19 -29]
 [-24  20  15]]
[[  7  31  27]
 [-15  19 -29]
 [-24  20  15]]


In [70]:
print(c*d)
print(np.multiply(c,d))

[[1794 2310  810]
 [3366 1802  546]
 [4480 7644 7426]]
[[1794 2310  810]
 [3366 1802  546]
 [4480 7644 7426]]


In [67]:
print(c/d)


[[1.17948718 1.88571429 2.5       ]
 [0.77272727 1.55882353 0.30952381]
 [0.7        1.25641026 1.18987342]]


ARRAY MANIPULATION

In [72]:
array=np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[9 7 0]
 [5 2 4]]
(2, 3)


In [73]:
trans=np.transpose(array)
print(trans)
print(trans.shape)

[[9 5]
 [7 2]
 [0 4]]
(3, 2)


another method

In [74]:
array=np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[6 4 7]
 [5 5 1]]
(2, 3)


In [78]:
trans2=array.T
print(trans2)
print(trans2.shape)

[[6 5]
 [4 5]
 [7 1]]
(3, 2)


Reshaping a Array 

In [79]:
a=np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[0 6 7]
 [7 6 4]]
(2, 3)


In [80]:
b=a.reshape(3,2)
print(b)
print(b.shape)

[[0 6]
 [7 7]
 [6 4]]
(3, 2)
